name: movielist
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  easy_search_bar: ^2.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  http: ^0.13.3
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/JsonFiles/deleted.json
    - assets/JsonFiles/movieDataCache.json
    - lib/src/

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/appIcon.png"
    min_sdk_android: 21 # android min sdk min:16, default 21

